version: '3.9'

services:

  app:
    image: nginx_part5:v1.3
    build:
      context: .
      dockerfile: Dockerfile

  server:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./part6/nginx.conf:/etc/nginx/nginx.conf